### ISSUE TITLE
Changing the port does not seem to work

### ISSUE THREAD

**Issue by frederickjh** [definitio/ha-rhvoice-addon#1]
The default port for this addon is 8080. In the Home Assistant GUI there is an option to change the port number I have another HA Addon that is using (forwarding) port 8080. So, when i tried to start this addon it would not start as it said that port 8080 was already in use. When I change the port number it starts but the log shows  that port 8080 is being used:

```
Setting trap PID 1
Chunked transfer encoding: False
Threads: 1
 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.30.33.6:8080
Press CTRL+C to quit
```
I have also tried to set the port number using the configuration instructions for the "RHVoice component for Home Assistant" (definitio/ ha-rhvoice), but this too does not seem to set the port. With some settings I get a 404 error with others a 500 error..

**Comment by definitio** [comment]
Logs will always show 8080 but you can change forwarding port.
Example:
1. Set addon port to 9999.
2. Set rhvoice integration port to 9999 (it must match)
3. Restart Home assistant

I tested and it works.

**Comment by frederickjh** [comment]
Thanks @definitio I tried this and it does work. I am guessing that the port set in the configuration is being forwarded to 8080 in the container which is why it will always have that in the log.

**Comment by definitio** [comment]
Yes, you're right.
