### ISSUE TITLE
[Question] Caching generated phrases, why?

### ISSUE THREAD

**Issue by 7floor** [definitio/ha-rhvoice-addon#3]
It seems that RHVoice addon caches generated files somewhere on file system:
Using HA Media Viewer's TTS feature:
- generate some phrase (phrase1) with anna - hear anna's voice
- switch voice to mikhail, reboot HA
- genereate another (phrase2) - hear mikhail's voice
- generate phrase1 again - hear anna, not mikhail(!)
And it seems impossible to hear phrase1 with mikhail voice anymore as it sounds with anna forever (until I add an extra space, for example). It obviously indicates caching.

Two issues with that:
- unable to regenerate same phrase with different voice
- usage of filesystem (I have HAOS on SD card)

One more thought - can it be made not to use real file system for mp3 generation at all? Can it use /tmp/cache or /dev/shm or whatever else on tmpfs instead? SD card life is a concern.

**Comment by definitio** [comment]
The addon doesn't use cache. It's HA cache. You can [disable](https://www.home-assistant.io/integrations/tts/#cache) it with `cache` option is action.
